config/routes.rb
Sirass::Application.routes.draw do

  get "t/visual", to: "test_pages#visual"
  get "t/info", to: "test_pages#info"

  get "reportes", to: 'reports#index'

  resources :prestadors, path: "prestadores"
  resources :institucion_users, path: "institucions"
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  resources :cprogramas do
    get 'internos',       to: 'cprogramas#index', internos: true, on: :collection
    get 'externos',       to: 'cprogramas#index', internos: false, on: :collection
    get 'cambiar_clave',  to: 'cprogramas#cambiar_clave', on: :member
    get 'search',         to: 'cprogramas#search', on: :collection
    member do
      get   'generar_nueva_clave',    to: 'cprogramas#generar_nueva_clave'
      match 'update_clave',           to: 'cprogramas#update_clave', via: :put
      match 'update_status/:status',  to: 'cprogramas#update_status'
      match 'update_observaciones',   to: 'cprogramas#update_observaciones'
      match 'print',                  to: 'cprogramas#print'
    end
  end

  match '/ayuda',     to: 'public_pages#ayuda'
  match '/programas', to: 'public_pages#programas'
  match '/proceso',   to: 'public_pages#proceso'

  match '/login',                 to: 'sessions#new'
  match '/logout',                to: 'sessions#destroy'
  match '/registro',              to: 'prestadors#new'
  match '/registro/institucion',  to: 'institucion_users#new'

  scope "/prestador" do
    get 'home',                 to: 'prestador_pages#index', as: :prestador_home
    get 'search',               to: 'prestadors#search', as: :prestador_search
    get 'inscripcion',          to: 'inscripcions#new', as: :inscripcion_servicio
    get 'Articulo_91',          to: 'articulos#new', as: :by_articulo
    get 'Articulo_91/delete',   to: 'articulos#delete'
    get 'Articulo91',           to: 'prestador_pages#ins_articulo', as: :mi_inscripcion_art
    get 'articulo/edit',        to: 'prestador_pages#edit_articulo'
    get 'mi_inscripcion',       to: 'prestador_pages#inscripcion'
    get 'mi_inscripcion/edit',  to: 'prestador_pages#edit_inscripcion'
    put 'estudianteUACM',       to: 'prestador_pages#estudianteDe'
    get 'reporte_horas',        to: 'prestador_pages#reporte_horas'
    get 'carta_compromiso',     to: 'prestador_pages#carta_compromiso'
    get 'solicitud_servicio',   to: 'prestador_pages#solicitud_servicio'

    resources :monthly_reports,     path: 'control_horas', as: 'control_horas' do
      member do
        get 'print'
      end
    end

    resources :bi_monthly_reports,  path: 'informe_bimensual', as: 'informe_bimensual' do
      member do
        get 'imprimir'
      end
    end
    get 'informe_final/new',        to: 'prestador_pages#new_informe_final'
    get 'informe_final/edit',       to: 'prestador_pages#edit_informe_final'
    match 'informe_final',          to: 'prestador_pages#create_informe_final', via: :post
    match 'informe_final',          to: 'prestador_pages#update_informe_final', via: :put
    get 'informe_final/ver',        to: 'prestador_pages#show_informe_final'
    get 'informe_final/print',      to: 'prestador_pages#print_informe_final'
  end

  scope "/institucion" do
    get 'home',         to: 'institucion_pages#index',      as: :institucion_home
    get 'actualizar_programas',   to: 'institucion_pages#actualizar', as: :actualizar_programa_institucion
    get 'avisos',     to: 'institucion_pages#avisos'
    get 'Cancelar_Paseo', to: 'institucion_pages#paseo', as: :desact_ins
    get 'Ayuda', to: 'institucion_pages#ayuda', as: :ayuda_ins
  end
  get '/admin/home',                  to: 'admin_pages#index'
  get '/admin/reportes_mensuales',    to: 'admin_pages#reportes_mensuales'
  get '/admin/reportes_bimensuales',  to: 'admin_pages#reportes_bimensuales'
  get '/admin/reportes_finales',      to: 'admin_pages#reportes_finales'

  match '/admin/reportes_mensuales/:id/cambiar_estado/:estado_id',  to: 'monthly_reports#cambiar_estado', as: :cambiar_estado_reporte, via: :put
  match '/admin/reportes_bimensuales/:id/cambiar_estado/:estado_id',  to: 'bi_monthly_reports#cambiar_estado', as: :cambiar_estado_reporte_bim, via: :put
  match '/admin/reportes_finales/:id/cambiar_estado/:estado_id',  to: 'final_reports#cambiar_estado', as: :cambiar_estado_reporte_fin, via: :put
  get '/Convocatoria', to: 'admin_pages#update_convocatoria'
  scope "/admin" do
    resources :institucions
    resources :plantels
    resources :final_reports, except: [:create, :new, :index] do
      get 'print', to: "final_reports#print", on: :member
    end
    resources :inscripcions,        path: "inscripciones" do
      match 'update_observaciones',   to: 'inscripcions#update_observaciones', via: :put
      match 'update_status/:status',  to: 'inscripcions#update_status', as: 'update_status'
      get   'generar_nuevo_ncontrol', to: 'inscripcions#generar_nuevo_ncontrol', as: 'generar_ncontrol'
      get   'calcular_horas_servicio', to: 'inscripcions#calcular_horas_servicio', as: 'calcular_horas_servicio'
      get   'reportes_mensuales',     to: 'inscripcions#reportes_mensuales', on: :member
      get   'reportes_bimensuales',     to: 'inscripcions#reportes_bimensuales', on: :member
    end
    resources :articulos, path: 'Articulo_91' do
      match 'Actualizar/:status',     to: 'articulos#update_stat', as: :update_stat
      match 'update_observaciones',   to: 'articulos#update_observaciones', via: :put
    end
  end

  root to: 'public_pages#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/final_report.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: final_reports
#
#  id                :integer          not null, primary key
#  inscripcion_id    :integer
#  estado_reporte_id :integer
#  horas             :string(255)
#  introduccion      :text
#  obj_gral          :text
#  obj_esp           :text
#  metodologia       :text
#  actividades       :text
#  metas             :text
#  resultados        :text
#  observaciones     :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class FinalReport < ActiveRecord::Base
  attr_accessible :actividades, :estado_reporte_id, :horas, :inscripcion_id, :introduccion,
  	:metas, :metodologia, :obj_esp, :obj_gral, :observaciones, :resultados

  validates_presence_of :actividades, :estado_reporte_id, :horas, :inscripcion_id, :introduccion,
  	:metas, :metodologia, :obj_esp, :obj_gral, :resultados

  belongs_to :inscripcion
  belongs_to :estado_reporte
  
end

app/controllers/final_reports_controller.rb
# encoding: utf-8
class FinalReportsController < ApplicationController

  before_filter :require_login
  layout :layout_for_report

  def index
  end

  def cambiar_estado
    authorize! :manage, FinalReport
    reporte = FinalReport.find( params[:id] )
    if reporte.update_attributes( estado_reporte_id: params[:estado_id] )
      flash[:success] = "Estado del reporte cambiado correctamente."
    else
      flash[:error] = "Ocurrió un error cambiando el estado del reporte"
    end
    redirect_to admin_reportes_finales_path
  end

  def update
    @reporte = FinalReport.find params[:id]
    params[:final_report][:estado_reporte_id] = EstadoReporte::CON_ERRORES
    
    if @reporte.update_attributes( params[:final_report] )
      flash[:success] = "Reporte actualizado correctamente."
    else
      flash[:error] = "Ocurrió un error actualizando los datos. Intenta nuevamente."
    end
    redirect_to final_report_path(@reporte)
  end

  def show
    @reporte = FinalReport.find(params[:id])
  end

  def edit
    @reporte = FinalReport.find(params[:id])
  end

  def destroy
    @reporte = FinalReport.find params[:id]
    if @reporte.destroy
      flash[:success] = "Reporte eliminado correctamente."
    else 
      flash[:error] = "No se pudo eliminar el reporte. Intenta nuevamente."
    end
    redirect_to informes_finales_path
  end

  def print
    @reporte = FinalReport.find params[:id]
    render layout: "print"
  end

  private 

    def layout_for_report

      if current_user.prestador
        "prestador"
      elsif current_user.admin
        "admin"
      else
        flash[:error] = "No puedes ver esta página"
        redirect_to current_user.user_page
      end
    end
end

app/helpers/final_reports_helper.rb
module FinalReportsHelper
end

app/views/final_reports/_admin_btn.html.erb
<div class="btn-group">
	<a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
		Administrar
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu left" role="menu" aria-labelledby="dLabel">
		<li>
			<%= link_to final_report_path(obj) do %>
				<i class="icon-eye-open"></i>
				Ver detalles
			<% end %>
		</li>
		<li>
			<%= link_to edit_final_report_path(obj) do %>
			<i class="icon-pencil"></i>
			Editar
			<% end %>
		</li>
		<li>
			<%= link_to print_final_report_path(obj) do %>
			<i class="icon-print"></i>
			Imprimir
			<% end %>
		</li>
		<li>
			<%= link_to final_report_path(obj), method: :delete, confirm: 'Estás seguro?' do %>
			<i class="icon-trash"></i>
			Eliminar
			<% end %>
		</li>
		<!-- CAMBIO DE ESTADO -->
		<li class="dropdown-submenu pull-left">
			<a href="#" tabindex="-1">
				<i class="icon-wrench"></i>
				Cambiar estado
			</a>
			<ul class="dropdown-menu">
				<% EstadoReporte.all.each do |e| %>
				<li>
					<%= link_to cambiar_estado_reporte_fin_path(obj, e.id), confirm: "Actualizando estado del reporte",
					method: :put do %>
						<i class="<%= icon_for_estado_reporte(e.id) %>"></i>
						<%= e.descripcion %>
					<% end %>
				</li>
				<% end %>
			</ul>
		</li>
	</ul>
</div>

app/views/final_reports/_fields.html.erb
<%= obj.input :horas, input_html: { class: "input-small" } %>
<%= obj.input :introduccion %>
<%= obj.input :obj_gral %>
<%= obj.input :obj_esp %>
<%= obj.input :metodologia %>
<%= obj.input :actividades %>
<%= obj.input :metas %>
<%= obj.input :resultados %>

app/views/final_reports/_observaciones.html.erb
<h4>Observaciones</h4>
<blockquote class="text-warning">
	<% if r.observaciones.blank? %>
		No se te hizo ninguna observación.
	<% else %>
		<%= simple_format h( r.observaciones ) %>
	<% end %>
</blockquote>

app/views/final_reports/_table.html.erb
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th class="center valign">Ver</th>
			<th class="center valign">Prestador</th>
			<th class="center valign">Horas reportadas</th>
			<th class="center valign">Estado</th>
			<th class="center valign">Acción</th>
		</tr>
	</thead>
	<tbody>
		<% reportes.each do |r| %>
		<tr>
			<td class="center valign">
				<%= link_to final_report_path(r) do  %>
					<i class="icon-eye-open"></i>
				<% end %>
			</td>
			<td class="valign">
				<%= link_to r.inscripcion.prestador.nombre_completo, r.inscripcion.prestador %>
			</td>
			<td class="center valign">
				<%= r.horas %>
			</td>
			<td class="center valign">
				<span class="label <%= lbl_estado_reporte(r) %>">
					<%= r.estado_reporte.descripcion %>
				</span>
			</td>
			<td class="center valign">
				<%= render 'final_reports/admin_btn', obj: r %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/final_reports/edit.html.erb
<% provide :title, "Editar Informe Final" %>

<h1>Editar Informe Final</h1>
<p class="lead">
	Si te hicieron observaciones debido a algún error en tu informe, desde aquí puedes actualizar los datos necesarios.
</p>

<%= render 'shared/observaciones', object: @reporte, url: final_report_path %>

<h2>Editar detalles del reporte</h2>

<%= simple_form_for @reporte, url: informe_final_path,
	defaults: { input_html: { class: 'input-block-level' } } do |f| %>
	<%= render 'fields', obj: f %>
	<div class="form-actions">
		<%= f.submit "Actualizar datos", class: "btn btn-success btn-block" %>
	</div>
<% end %>

app/views/final_reports/index.html.erb
<h1>FinalReports#index</h1>
<p>Find me in app/views/final_reports/index.html.erb</p>

app/views/final_reports/print.html.erb
<% provide :title, "INFORME FINAL DE ACTIVIDADES" %>

<div class="row">
	<div class="span2">
		<p>
			<strong>Inscripción:</strong> #<%= @reporte.inscripcion.id %>
		</p>
	</div>
	<div class="span5 offset1">
		<p>
			<strong>Prestador:</strong> <%= @reporte.inscripcion.prestador.nombre_completo %>
		</p>
	</div>
</div>
<p>
	<strong>Estado:</strong>
	<span class="label <%= lbl_estado_reporte(@reporte) %>">
		<%= @reporte.estado_reporte.descripcion %>
	</span>
</p>
<hr>
<p>
	<strong>Horas:</strong> <%= @reporte.horas %>
</p>

<h4>Introducción</h4>
<%= simple_format h( @reporte.introduccion ) %>

<h4>Objetivo General</h4>
<%= simple_format h( @reporte.obj_gral ) %>

<h4>Objetivos Específicos</h4>
<%= simple_format h( @reporte.obj_esp ) %>

<h4>Metodología</h4>
<%= simple_format h( @reporte.metodologia ) %>

<h4>Actividades realizadas</h4>
<%= simple_format h( @reporte.actividades ) %>

<h4>Metas</h4>
<%= simple_format h( @reporte.metas ) %>

<h4>Resultados y Conclusiones</h4>
<%= simple_format h( @reporte.resultados ) %>

<table class="table table-bordered" id="firmas">
	<thead>
		<tr>
			<th colspan="3">AUTORIZACIÓN</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<span class="placeholder"></span>
			</td>
			<td>
				<span class="placeholder"></span>
			</td>
			<td>
				<span class="placeholder"></span>
			</td>
		</tr>
		<tr>
			<td>
				<span class="muted">Firma del prestador de Servicio Social</span>
			</td>
			<td>
				<span class="muted">(Nombre, Firma y Cargo del Responsable del Programa)</span>
			</td>
			<td>
				<span class="muted">Responsable de la Oficina de Servicio Social de la UACM</span>
			</td>
		</tr>
		<tr>
			<td>
				<span class="placeholder"></span>
			</td>
			<td rowspan="2">
				<strong class="sello">SELLO</strong>
			</td>
			<td rowspan="2">
				<strong class="sello">SELLO</strong>
			</td>
		</tr>
		<tr>
			<td>
				<span class="muted">(Nombre, firma y Cargo del Supervisor o Jefe Inmediato)</span>
			</td>
		</tr>
	</tbody>
</table>

<p>
	Ciudad de México, Distrito Federal a los <span class="date"><%= l Date.today, format: :full %>, <%= l Time.now, format: :short %></span>.
</p>

<strong class="pull-right">Formato 011</strong>

app/views/final_reports/show.html.erb
<% provide :title, "Ver Informe Final" %>

<h1>Informe Final de Actividades</h1>
<p class="lead">
	A continuación se muestran los detalles de tu <em>Informe Final de Actividades</em>.
</p>
<div class="row">
	<div class="span2">
		<p>
			<strong>Inscripción:</strong> <%= link_to "##{@reporte.inscripcion.id}", @reporte.inscripcion %>
		</p>
	</div>
	<div class="span5 offset1">
		<p>
			<strong>Prestador:</strong> <%= link_to @reporte.inscripcion.prestador.nombre_completo, @reporte.inscripcion.prestador %>
		</p>
	</div>
</div>
<p class="pull-right">
<% if can? :manage, FinalReport %>
	<%= render 'admin_btn', obj: @reporte %>
<% else %>
	<%= link_to informe_final_edit_path, class: 'btn btn-primary' do %>
		<i class="icon-pencil"></i>
		Editar
	<% end %>
	<%= link_to informe_final_print_path, class: 'btn btn-primary' do %>
		<i class="icon-print"></i>
		Imprimir
	<% end %>
<% end %>
</p>
<p>
	<strong>Estado:</strong>
	<span class="label <%= lbl_estado_reporte(@reporte) %>">
		<%= @reporte.estado_reporte.descripcion %>
	</span>
</p>
<hr>
<%= render 'observaciones', r: @reporte %>
<hr>
<p>
	<strong>Horas:</strong> <%= @reporte.horas %>
</p>

<h4>Introducción</h4>
<%= simple_format h( @reporte.introduccion ) %>

<h4>Objetivo General</h4>
<%= simple_format h( @reporte.obj_gral ) %>

<h4>Objetivos Específicos</h4>
<%= simple_format h( @reporte.obj_esp ) %>

<h4>Metodología</h4>
<%= simple_format h( @reporte.metodologia ) %>

<h4>Actividades realizadas</h4>
<%= simple_format h( @reporte.actividades ) %>

<h4>Metas</h4>
<%= simple_format h( @reporte.metas ) %>

<h4>Resultados y Conclusiones</h4>
<%= simple_format h( @reporte.resultados ) %>

<% if can? :manage, FinalReport %>
	<%= render 'shared/observaciones', object: @reporte, url: final_report_path(@reporte) %>
	<%= render 'shared/back_button', link: admin_reportes_finales_path %>
<% end %>