config/routes.rb
Sirass::Application.routes.draw do

  get "t/visual", to: "test_pages#visual"
  get "t/info", to: "test_pages#info"

  get "reportes", to: 'reports#index'

  resources :prestadors, path: "prestadores"
  resources :institucion_users, path: "institucions"
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  resources :cprogramas do
    get 'internos',       to: 'cprogramas#index', internos: true, on: :collection
    get 'externos',       to: 'cprogramas#index', internos: false, on: :collection
    get 'cambiar_clave',  to: 'cprogramas#cambiar_clave', on: :member
    get 'search',         to: 'cprogramas#search', on: :collection
    member do
      get   'generar_nueva_clave',    to: 'cprogramas#generar_nueva_clave'
      match 'update_clave',           to: 'cprogramas#update_clave', via: :put
      match 'update_status/:status',  to: 'cprogramas#update_status'
      match 'update_observaciones',   to: 'cprogramas#update_observaciones'
      match 'print',                  to: 'cprogramas#print'
    end
  end

  match '/ayuda',     to: 'public_pages#ayuda'
  match '/programas', to: 'public_pages#programas'
  match '/proceso',   to: 'public_pages#proceso'

  match '/login',                 to: 'sessions#new'
  match '/logout',                to: 'sessions#destroy'
  match '/registro',              to: 'prestadors#new'
  match '/registro/institucion',  to: 'institucion_users#new'

  scope "/prestador" do
    get 'home',                 to: 'prestador_pages#index', as: :prestador_home
    get 'search',               to: 'prestadors#search', as: :prestador_search
    get 'inscripcion',          to: 'inscripcions#new', as: :inscripcion_servicio
    get 'Articulo_91',          to: 'articulos#new', as: :by_articulo
    get 'Articulo_91/delete',   to: 'articulos#delete'
    get 'Articulo91',           to: 'prestador_pages#ins_articulo', as: :mi_inscripcion_art
    get 'articulo/edit',        to: 'prestador_pages#edit_articulo'
    get 'mi_inscripcion',       to: 'prestador_pages#inscripcion'
    get 'mi_inscripcion/edit',  to: 'prestador_pages#edit_inscripcion'
    put 'estudianteUACM',       to: 'prestador_pages#estudianteDe'
    get 'reporte_horas',        to: 'prestador_pages#reporte_horas'
    get 'carta_compromiso',     to: 'prestador_pages#carta_compromiso'
    get 'solicitud_servicio',   to: 'prestador_pages#solicitud_servicio'

    resources :monthly_reports,     path: 'control_horas', as: 'control_horas' do
      member do
        get 'print'
      end
    end

    resources :bi_monthly_reports,  path: 'informe_bimensual', as: 'informe_bimensual' do
      member do
        get 'imprimir'
      end
    end
    get 'informe_final/new',        to: 'prestador_pages#new_informe_final'
    get 'informe_final/edit',       to: 'prestador_pages#edit_informe_final'
    match 'informe_final',          to: 'prestador_pages#create_informe_final', via: :post
    match 'informe_final',          to: 'prestador_pages#update_informe_final', via: :put
    get 'informe_final/ver',        to: 'prestador_pages#show_informe_final'
    get 'informe_final/print',      to: 'prestador_pages#print_informe_final'
  end

  scope "/institucion" do
    get 'home',         to: 'institucion_pages#index',      as: :institucion_home
    get 'actualizar_programas',   to: 'institucion_pages#actualizar', as: :actualizar_programa_institucion
    get 'avisos',     to: 'institucion_pages#avisos'
    get 'Cancelar_Paseo', to: 'institucion_pages#paseo', as: :desact_ins
    get 'Ayuda', to: 'institucion_pages#ayuda', as: :ayuda_ins
  end
  get '/admin/home',                  to: 'admin_pages#index'
  get '/admin/reportes_mensuales',    to: 'admin_pages#reportes_mensuales'
  get '/admin/reportes_bimensuales',  to: 'admin_pages#reportes_bimensuales'
  get '/admin/reportes_finales',      to: 'admin_pages#reportes_finales'

  match '/admin/reportes_mensuales/:id/cambiar_estado/:estado_id',  to: 'monthly_reports#cambiar_estado', as: :cambiar_estado_reporte, via: :put
  match '/admin/reportes_bimensuales/:id/cambiar_estado/:estado_id',  to: 'bi_monthly_reports#cambiar_estado', as: :cambiar_estado_reporte_bim, via: :put
  match '/admin/reportes_finales/:id/cambiar_estado/:estado_id',  to: 'final_reports#cambiar_estado', as: :cambiar_estado_reporte_fin, via: :put
  get '/Convocatoria', to: 'admin_pages#update_convocatoria'
  scope "/admin" do
    resources :institucions
    resources :plantels
    resources :final_reports, except: [:create, :new, :index] do
      get 'print', to: "final_reports#print", on: :member
    end
    resources :inscripcions,        path: "inscripciones" do
      match 'update_observaciones',   to: 'inscripcions#update_observaciones', via: :put
      match 'update_status/:status',  to: 'inscripcions#update_status', as: 'update_status'
      get   'generar_nuevo_ncontrol', to: 'inscripcions#generar_nuevo_ncontrol', as: 'generar_ncontrol'
      get   'calcular_horas_servicio', to: 'inscripcions#calcular_horas_servicio', as: 'calcular_horas_servicio'
      get   'reportes_mensuales',     to: 'inscripcions#reportes_mensuales', on: :member
      get   'reportes_bimensuales',     to: 'inscripcions#reportes_bimensuales', on: :member
    end
    resources :articulos, path: 'Articulo_91' do
      match 'Actualizar/:status',     to: 'articulos#update_stat', as: :update_stat
      match 'update_observaciones',   to: 'articulos#update_observaciones', via: :put
    end
  end

  root to: 'public_pages#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/monthly_report.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: monthly_reports
#
#  id                :integer          not null, primary key
#  numero            :integer
#  inscripcion_id    :integer
#  estado_reporte_id :integer
#  horas             :string(255)
#  horas_acum        :string(255)
#  horas_anteriores  :string(255)
#  supervisor        :string(255)
#  fecha_inicio      :date
#  fecha_fin         :date
#  observaciones     :text(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class MonthlyReport < ActiveRecord::Base
  attr_accessible :estado_reporte_id, :fecha_fin, :fecha_inicio, :horas, :horas_acum, :horas_anteriores, :inscripcion_id, :numero, :observaciones, :supervisor, :monthly_report_hours_attributes

  validates_presence_of :fecha_fin, :fecha_inicio, :horas, :horas_acum, :horas_anteriores, :inscripcion_id, :numero, :supervisor

  validates :numero, numericality: { only_integer: true, greater_than: 0, less_than: 11 }

  belongs_to :inscripcion
  belongs_to :estado_reporte
  has_many :monthly_report_hours, dependent: :destroy
  accepts_nested_attributes_for :monthly_report_hours, allow_destroy: true
  validates_associated :monthly_report_hours

  after_save :update_horas_servicio
  after_destroy :update_horas_servicio

  private
	  def update_horas_servicio
	  	self.inscripcion.calcular_horas_servicio
	  end
end

app/controllers/monthly_reports_controller.rb
# encoding: utf-8
include MonthlyReportsHelper
class MonthlyReportsController < ApplicationController
  before_filter :require_login
  before_filter :require_inscripcion_activa, only: [:new, :create, :index]
  layout 'prestador'

  def index
    require_role :prestador
    p = current_user.prestador
    @reportes = MonthlyReport.where(inscripcion_id: p.inscripcion_actual)
  end

  def new
    require_role :prestador
    @control_horas = MonthlyReport.new
    # Comenzar en el primer día del mes pasado o del mes que se envíe por parámetro
    today = Date.today
    anterior = today.prev_month
    anterior = Date.new(anterior.year, anterior.month, 1)
    mes_inicio = anterior.month
    anio_inicio = anterior.year
    inteligente = false
    if params[:date] && params[:date][:mes].to_i > 0 &&
      params[:date][:anio].to_i > 0
        mes_inicio = params[:date][:mes].to_i
        anio_inicio = params[:date][:anio].to_i
        anterior = Date.new(anio_inicio, mes_inicio, 1)
        inteligente = true
    end
    
    # Llenado inteligente del mes seleccionado y sólo días de la semana
    if inteligente
      dias = dias_para_mes(mes_inicio, anio_inicio) 
      @control_horas.horas = "80:00"
      dias_enum = dias.to_enum
      horas = 0
      while horas < 80
        d = dias_enum.next
        registro = @control_horas.monthly_report_hours.build
        registro.fecha = d
        registro.entrada = "08:00"
        registro.salida = "12:00"
        horas += 4
      end
    else
      registro = @control_horas.monthly_report_hours.build
      registro.entrada = "08:00"
      registro.salida = "12:00"
      @control_horas.horas = "04:00"
    end

    inscripcion = current_user.prestador.inscripcion_actual

    reportes = MonthlyReport.where(inscripcion_id: inscripcion).order("created_at ASC")

    numero = 1 + reportes.size
    reporte_anterior = reportes.first
    hanteriores = "00:00"
    hanteriores = reporte_anterior.horas if reporte_anterior
    @control_horas.numero = numero
    @control_horas.fecha_inicio = anterior
    @control_horas.fecha_fin = anterior.next_month
    @control_horas.horas_anteriores = hanteriores
  end

  def edit
    @control_horas = MonthlyReport.find(params[:id])
    if current_user.prestador
      inscripcion = Inscripcion.find(current_user.prestador.inscripcion_actual)
      if not inscripcion.monthly_reports.include? @control_horas
        redirect_to control_horas_path
      end
    else
      authorize! :manage, MonthlyReport
      render layout: 'admin'
    end
  end

  def create
    @control_horas = MonthlyReport.new(params[:monthly_report])
    @control_horas.inscripcion_id = current_user.prestador.inscripcion_actual
    @control_horas.estado_reporte_id = EstadoReporte::SIN_REVISION
    if @control_horas.save
      flash[:success] = "Control de Horas guardado correctamente"
      redirect_to control_horas_path
    else
      flash.now[:error] = "Ocurrió un error guardando el registro..."
      render 'new'
    end
  end

  def update
    @control_horas = MonthlyReport.find(params[:id])
    params[:monthly_report][:estado_reporte_id] = EstadoReporte::ACTUALIZADO
    if params[:monthly_report][:observaciones]
      params[:monthly_report][:estado_reporte_id] = EstadoReporte::CON_ERRORES
    end
    
    if @control_horas.update_attributes(params[:monthly_report])
      flash[:success] = "Reporte actualizado correctamente"
      redirect_to current_user.user_page
    else
      flash[:error] = "Ocurrió un error actualizando tu reporte."
      render :edit
    end
  end

  def destroy
    @control_horas = MonthlyReport.find(params[:id])
    puede_eliminar = false
    if current_user.prestador
      inscripcion = Inscripcion.find(current_user.prestador.inscripcion_actual)
      puede_eliminar = true if inscripcion.monthly_reports.include? @control_horas
    else
      authorize! :manage, MonthlyReport
      puede_eliminar = true
    end
    
    if puede_eliminar
      if @control_horas.destroy
        flash[:success] = "Reporte eliminado correctamente"
      else
        flash[:error] = "No se pudo eliminar el reporte, ocurrió un error."
      end
    end
    redirect_to current_user.user_page
  end

  def show
    @reporte = MonthlyReport.find(params[:id])
    if current_user.admin
      render layout: 'admin'
    end
  end

  def print
    allow = false
    @reporte = MonthlyReport.find(params[:id])
    @inscripcion = @reporte.inscripcion
    @programa = @inscripcion.cprograma
    @prestador = @inscripcion.prestador

    if can? :manage, MonthlyReport
      allow = true
    end
    if current_user.prestador && current_user.prestador.id == @reporte.inscripcion.prestador.id
      allow = true
    end
    
    if allow
      render layout: 'print'
    else
      flash[:error] = "¡No puedes imprimir este reporte!"
      redirect_to current_user.user_page
    end
  end

  def cambiar_estado
    authorize! :manage, MonthlyReport
    reporte = MonthlyReport.find( params[:id] )
    if reporte.update_attributes( estado_reporte_id: params[:estado_id] )
      flash[:success] = "Estado del reporte cambiado correctamente."
    else
      flash[:error] = "Ocurrió un error cambiando el estado del reporte"
    end
    redirect_to admin_reportes_mensuales_path
  end

  private
    # Obtener una lista de todos los días de un mes sin incluir los fines de semana
    def dias_para_mes(mes, anio)
      fecha = Date.new(anio, mes, 1)
      fecha_termino = fecha.next_month
      dias = []
      while (fecha <=> fecha_termino) != 0
        dias << fecha if not (fecha.saturday? or fecha.sunday?)
        fecha = fecha + 1
      end
      return dias
    end
end

app/helpers/monthly_reports_helper.rb
module MonthlyReportsHelper
end

app/views/monthly_reports/_admin_btn.html.erb
<div class="btn-group btn-block admin-btn">
	<a href="#" class="btn btn-primary btn-block dropdown-toggle" data-toggle="dropdown">
		<i class="icon-cog"></i>
		Administrar
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu left" role="menu" aria-labelledby="dLabel">
		<li>
			<%= link_to control_hora_path(obj) do %>
				<i class="icon-eye-open"></i>
				Ver detalles
			<% end %>
		</li>
		<li>
			<%= link_to print_control_hora_path(obj) do %>
				<i class="icon-print"></i>
				Imprimir
			<% end %>
		</li>
		<li>
			<%= link_to edit_control_hora_path(obj) do %>
			<i class="icon-pencil"></i>
			Editar
			<% end %>
		</li>
		<li>
			<%= link_to control_hora_path(obj), method: :delete, confirm: 'Estás seguro?' do %>
			<i class="icon-trash"></i>
			Eliminar
			<% end %>
		</li>
		<% if can? :manage, MonthlyReport %>
		<!-- CAMBIO DE ESTADO -->
		<li class="dropdown-submenu pull-left">
			<a href="#" tabindex="-1">
				<i class="icon-wrench"></i>
				Cambiar estado
			</a>
			<ul class="dropdown-menu">
				<% EstadoReporte.all.each do |e| %>
				<li>
					<%= link_to cambiar_estado_reporte_path(obj, e.id), confirm: "Actualizando estado del reporte",
					method: :put do %>
						<i class="<%= icon_for_estado_reporte(e.id) %>"></i>
						<%= e.descripcion %>
					<% end %>
				</li>
				<% end %>
			</ul>
		</li>
		<% end %>
	</ul>
</div>

app/views/monthly_reports/_fields.html.erb
<div class="row">
	<div class="span2">
		<%= f.input :numero, input_html: { max: 10, min: 1, autofocus: true } %>
	</div>
	<div class="span2 offset1">
		<%= f.input :fecha_inicio do %>
			<div class="input-append bootstrap-timepicker-component">
				<%= f.text_field :fecha_inicio, 'data-behaviour' => 'datepicker', class: 'input-small', placeholder: "dd/mm/aaaa", value: f.object.fecha_inicio.to_s %>
				<span class="add-on">
		  			<i class="icon-calendar"></i>
		  		</span>
			</div>
		<% end %>
	</div>
	<div class="span2 offset1">
		<%= f.input :fecha_fin do %>
			<div class="input-append bootstrap-timepicker-component">
				<%= f.text_field :fecha_fin, 'data-behaviour' => 'datepicker', class: 'input-small', placeholder: "dd/mm/aaaa", value: f.object.fecha_fin.to_s %>
				<span class="add-on">
		  			<i class="icon-calendar"></i>
		  		</span>
			</div>
		<% end %>
	</div>
</div>

<%= f.input :supervisor %>

app/views/monthly_reports/_fields_horas.html.erb
<!-- RESUMEN DE HORAS -->
<div class="row">
	<div class="span2">
		<%= f.input :horas do %>
			<div class="input-append">
				<%= f.text_field :horas, class: 'input-mini right', placeholder: "HH:MM" %>
				<span class="add-on">
		  			<i class="icon-time"></i>
		  		</span>
			</div>
		<% end %>
	</div>
	<div class="span2 offset1">
		<%= f.input :horas_anteriores do %>
			<div class="input-append">
				<%= f.text_field :horas_anteriores, class: 'input-mini right', placeholder: "HHH:MM" %>
				<span class="add-on">
		  			<i class="icon-time"></i>
		  		</span>
			</div>
		<% end %>
	</div>
	<div class="span2 offset1">
		<%= f.input :horas_acum do %>
			<div class="input-append">
				<%= f.text_field :horas_acum, class: 'input-mini right', placeholder: "HHH:MM" %>
				<span class="add-on">
		  			<i class="icon-time"></i>
		  		</span>
			</div>
		<% end %>
	</div>
</div>

<!-- ACCIONES -->
<div class="well well-small center">
	<%= link_to_add_fields "Agregar hora", f, :monthly_report_hours %>
</div>

<!-- REGISTROS DE HORAS -->
<table class="table table-bordered table-condensed" id="table_horas">
	<thead>
		<tr>
			<th>Fecha</th>
			<th>Hora de entrada</th>
			<th>Hora de salida</th>
			<th>Eliminar</th>
		</tr>
	</thead>
	<tbody>
	<%= f.simple_fields_for :monthly_report_hours do |builder| %>
		<%= render 'monthly_report_hour_fields', f: builder %>
	<% end %>
	</tbody>
</table>

app/views/monthly_reports/_monthly_report_hour_fields.html.erb
<tr>
	<td>
		<%= f.hidden_field :_destroy, as: :hidden, value: false %>
		<%= f.input :fecha, label: false do %>
			<div class="input-append bootstrap-timepicker-component">
				<%= f.text_field :fecha, 'data-behaviour' => 'datepicker', class: 'input-small', placeholder: "dd/mm/aaaa", value: f.object.fecha.to_s %>
				<span class="add-on">
		  			<i class="icon-calendar"></i>
		  		</span>
			</div>
		<% end %>
	</td>
	<td class="center valign">
		
		<%= f.input :entrada, label: false, input_html: { class: 'input-mini', onChange: 'calcularTiempo()' } %>
	</td>
	<td class="center valign">
		
		<%= f.input :salida, label: false, input_html: { class: 'input-mini', onChange: 'calcularTiempo()' } %>
	</td>
	<td class="center valign">
		<button type="button" onclick='remove_hour(this, <%= f.object.new_record? %>)' class="btn btn-danger btn-mini btn-block">
			<i class="icon-remove"></i>
			Eliminar
		</button>
	</td>
</tr>

app/views/monthly_reports/_table.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Ver</th>
			<% if can? :manage, MonthlyReport %>
			<th>Prestador</th>
			<% end %>
			<th>De</th>
			<th>A</th>
			<th>Horas</th>
			<th>Estado</th>
			<th>Acción</th>
		</tr>
	</thead>
	<tbody>
	<% reportes.each do |r| %>
		<tr>
			<td class="valign center">
				<%= link_to control_hora_path(r) do %>
				<i class="icon-eye-open"></i>
				<% end %>
			</td>
			<% if can? :manage, MonthlyReport %>
			<td class="valign">
				<%= link_to r.inscripcion.prestador.nombre_completo, r.inscripcion.prestador %>
			</td>
			<% end %>
			<td class="valign">
				<%= r.fecha_inicio %>
			</td>
			<td class="valign">
				<%= r.fecha_fin %>
			</td>
			<td class="valign">
				<%= r.horas %>
			</td>
			<td class="center valign">
				<span class="label <%= lbl_estado_reporte(r) %>">
					<%= r.estado_reporte.descripcion %>
				</span>
			</td>
			<td class="valign">
				<%= render 'monthly_reports/admin_btn', obj: r %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/monthly_reports/_table_hours.html.erb
<table class="table table-bordered table-striped table-condensed">
	<thead>
		<tr>
			<th class="center">Fecha</th>
			<th class="center">Entrada</th>
			<th class="center">Salida</th>
		</tr>
	</thead>
	<tbody>
	<% @reporte.monthly_report_hours.each do |r| %>
		<tr>
			<td class="center"><%= r.fecha %></td>
			<td class="center"><%= r.entrada.strftime("%H:%M")	 %></td>
			<td class="center"><%= r.salida.strftime("%H:%M") %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/monthly_reports/create.html.erb
<h1>MonthlyReports#create</h1>
<p>Find me in app/views/monthly_reports/create.html.erb</p>

app/views/monthly_reports/edit.html.erb
<% provide(:title, "Envio de Control de Horas") %>
<% provide(:sidebar_active, :control_horas) %>
<% content_for :javascript do  %>
	<%= javascript_include_tag 'monthly_reports' %>
<% end %>

<h1>Actualizar Control Mensual de Horas</h1>
<p>
	Corrige los datos necesarios para modificar tu reporte.
</p>

<%= render 'shared/error_messages', object: @control_horas %>
<%= simple_form_for @control_horas, defaults: { input_html: { class: 'input-block-level' } }, url: control_hora_path(@control_horas) do |f| %>
	<!-- TABS -->
	<ul class="nav nav-tabs" id="tabs">
		<li class="active">
			<a href="#tab_general" data-toggle="tab">Datos generales</a>
		</li>
		<li>
			<a href="#tab_horas" data-toggle="tab">Registro de horas</a>
		</li>
	</ul>
	<!-- TABS CONTENTS -->
	<div class="tab-content">
		<!-- DATOS GENERALES DEL REPORTE -->
		<div class="tab-pane active" id="tab_general">
			<%= render 'fields', f: f %>
			<div class="well well-small center">
				Para continuar pulsa la pestaña
				<strong>
					<%= link_to_function 'Registro de Horas', "$('#tabs a:last').tab('show')" %>
				</strong>
			</div>
		</div>

		<!-- REGISTRO DE HORAS DEL REPORTE -->
		<div class="tab-pane" id="tab_horas">
			<%= render 'fields_horas', f: f %>
			<div class="form-actions">
				<%= f.submit "Actualizar reporte", class: 'btn btn-success' %>
			</div>
		</div>
	</div>
<% end %>

app/views/monthly_reports/index.html.erb
<% provide(:sidebar_active, :revControl) %>
<h1>Control Mensual de Horas</h1>
<% if @reportes.any? %>
<p class="lead">Lista de todos los reportes que haz enviado</p>
<%= render 'table', reportes: @reportes %>
<% else %>
<p class="lead">
	No haz enviado ningún reporte todavía.
</p>
<% end %>

app/views/monthly_reports/new.html.erb
<% provide(:title, "Envio de Control de Horas") %>
<% content_for :javascript do  %>
	<%= javascript_include_tag 'monthly_reports' %>
<% end %>

<h1>Enviar Control Mensual de Horas</h1>
<p>
	Por favor llena la siguiente información para generar tu <em>Control Mensual de Horas.</em>
</p>

<%= render 'shared/error_messages', object: @control_horas %>
<%= simple_form_for @control_horas, defaults: { input_html: { class: 'input-block-level' } }, url: control_horas_path do |f| %>
	<!-- TABS -->
	<ul class="nav nav-tabs" id="tabs">
		<li class="active">
			<a href="#tab_general" data-toggle="tab">Datos generales</a>
		</li>
		<li>
			<a href="#tab_horas" data-toggle="tab">Registro de horas</a>
		</li>
	</ul>
	<!-- TABS CONTENTS -->
	<div class="tab-content">
		<!-- DATOS GENERALES DEL REPORTE -->
		<div class="tab-pane active" id="tab_general">
			<%= render 'fields', f: f %>
			<div class="well well-small center">
				Para continuar pulsa la pestaña
				<strong>
					<%= link_to_function 'Registro de Horas', "$('#tabs a:last').tab('show')" %>
				</strong>
			</div>
		</div>

		<!-- REGISTRO DE HORAS DEL REPORTE -->
		<div class="tab-pane" id="tab_horas">
			<%= render 'fields_horas', f: f %>
			<div class="form-actions">
				<%= f.submit "Enviar reporte", class: 'btn btn-success' %>
			</div>
		</div>
	</div>
<% end %>

app/views/monthly_reports/show.html.erb
<% provide(:title, "Detalles de Control de Horas") %>
<h1>Detalles del reporte</h1>
<p class="lead">
	A continuación se presentan los detalles del <strong><em>Control Mensual de Horas</em></strong>.
</p>
<div class="row">
	<div class="span2">
		<p>
			<strong>Inscripción:</strong> <%= link_to "##{@reporte.inscripcion.id}", @reporte.inscripcion %>
		</p>
	</div>
	<div class="span5 offset1">
		<p>
			<strong>Prestador:</strong> <%= link_to @reporte.inscripcion.prestador.nombre_completo, @reporte.inscripcion.prestador %>
		</p>
	</div>
</div>
<p>
	<strong>Número:</strong> <%= @reporte.numero %>
</p>

<div class="row">
	<div class="span3">
		<strong>Periodo del:</strong>
		<%= @reporte.fecha_inicio %>
	</div>
	<div class="span3">
		<strong>Al:</strong>
		<%= @reporte.fecha_fin %>
	</div>
	<div class="span2">
		<strong>Estado:</strong>
		<span class="label <%= lbl_estado_reporte(@reporte) %>">
			<%= @reporte.estado_reporte.descripcion %>
		</span>
	</div>
</div>
<br>
<div class="row">
	<div class="span2">
		<strong>Horas:</strong>
		<p class="well well-small center">
			<%= @reporte.horas %>
		</p>
	</div>
	<div class="span2 offset1">
		<strong>Horas anteriores:</strong>
		<p class="well well-small center">
			<%= @reporte.horas_anteriores %>
		</p>
	</div>
	<div class="span2 offset1">
		<strong>Horas acumuladas:</strong>
		<p class="well well-small center">
			<%= @reporte.horas_acum %>
		</p>
	</div>
</div>
<p>
	<strong>Supervisor:</strong>
	<%= @reporte.supervisor %>
</p>
<div class="pull-right span2">
	<%= render 'admin_btn', obj: @reporte %>
</div>
<h2>Registro de Horas</h2>

<table class="table table-bordered table-striped table-condensed">
	<thead>
		<tr>
			<th class="center">Fecha</th>
			<th class="center">Entrada</th>
			<th class="center">Salida</th>
		</tr>
	</thead>
	<tbody>
	<% @reporte.monthly_report_hours.each do |r| %>
		<tr>
			<td class="center"><%= r.fecha %></td>
			<td class="center"><%= r.entrada.strftime("%H:%M")	 %></td>
			<td class="center"><%= r.salida.strftime("%H:%M") %></td>
		</tr>
	<% end %>
	</tbody>
</table>
<% if can? :manage, MonthlyReport %>
	<%= render 'shared/observaciones', object: @reporte, url: control_hora_path(@reporte) %>
	<%= render 'shared/back_button', link: admin_reportes_mensuales_path %>
<% end %>

app/views/monthly_reports/update.html.erb
<h1>MonthlyReports#update</h1>
<p>Find me in app/views/monthly_reports/update.html.erb</p>