config/routes.rb
Sirass::Application.routes.draw do

  get "t/visual", to: "test_pages#visual"
  get "t/info", to: "test_pages#info"

  get "reportes", to: 'reports#index'

  resources :prestadors, path: "prestadores"
  resources :institucion_users, path: "institucions"
  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  resources :cprogramas do
    get 'internos',       to: 'cprogramas#index', internos: true, on: :collection
    get 'externos',       to: 'cprogramas#index', internos: false, on: :collection
    get 'cambiar_clave',  to: 'cprogramas#cambiar_clave', on: :member
    get 'search',         to: 'cprogramas#search', on: :collection
    member do
      get   'generar_nueva_clave',    to: 'cprogramas#generar_nueva_clave'
      match 'update_clave',           to: 'cprogramas#update_clave', via: :put
      match 'update_status/:status',  to: 'cprogramas#update_status'
      match 'update_observaciones',   to: 'cprogramas#update_observaciones'
      match 'print',                  to: 'cprogramas#print'
    end
  end

  match '/ayuda',     to: 'public_pages#ayuda'
  match '/programas', to: 'public_pages#programas'
  match '/proceso',   to: 'public_pages#proceso'

  match '/login',                 to: 'sessions#new'
  match '/logout',                to: 'sessions#destroy'
  match '/registro',              to: 'prestadors#new'
  match '/registro/institucion',  to: 'institucion_users#new'

  scope "/prestador" do
    get 'home',                 to: 'prestador_pages#index', as: :prestador_home
    get 'search',               to: 'prestadors#search', as: :prestador_search
    get 'inscripcion',          to: 'inscripcions#new', as: :inscripcion_servicio
    get 'Articulo_91',          to: 'articulos#new', as: :by_articulo
    get 'Articulo_91/delete',   to: 'articulos#delete'
    get 'Articulo91',           to: 'prestador_pages#ins_articulo', as: :mi_inscripcion_art
    get 'articulo/edit',        to: 'prestador_pages#edit_articulo'
    get 'mi_inscripcion',       to: 'prestador_pages#inscripcion'
    get 'mi_inscripcion/edit',  to: 'prestador_pages#edit_inscripcion'
    put 'estudianteUACM',       to: 'prestador_pages#estudianteDe'
    get 'reporte_horas',        to: 'prestador_pages#reporte_horas'
    get 'carta_compromiso',     to: 'prestador_pages#carta_compromiso'
    get 'solicitud_servicio',   to: 'prestador_pages#solicitud_servicio'

    resources :monthly_reports,     path: 'control_horas', as: 'control_horas' do
      member do
        get 'print'
      end
    end

    resources :bi_monthly_reports,  path: 'informe_bimensual', as: 'informe_bimensual' do
      member do
        get 'imprimir'
      end
    end
    get 'informe_final/new',        to: 'prestador_pages#new_informe_final'
    get 'informe_final/edit',       to: 'prestador_pages#edit_informe_final'
    match 'informe_final',          to: 'prestador_pages#create_informe_final', via: :post
    match 'informe_final',          to: 'prestador_pages#update_informe_final', via: :put
    get 'informe_final/ver',        to: 'prestador_pages#show_informe_final'
    get 'informe_final/print',      to: 'prestador_pages#print_informe_final'
  end

  scope "/institucion" do
    get 'home',         to: 'institucion_pages#index',      as: :institucion_home
    get 'actualizar_programas',   to: 'institucion_pages#actualizar', as: :actualizar_programa_institucion
    get 'avisos',     to: 'institucion_pages#avisos'
    get 'Cancelar_Paseo', to: 'institucion_pages#paseo', as: :desact_ins
    get 'Ayuda', to: 'institucion_pages#ayuda', as: :ayuda_ins
  end
  get '/admin/home',                  to: 'admin_pages#index'
  get '/admin/reportes_mensuales',    to: 'admin_pages#reportes_mensuales'
  get '/admin/reportes_bimensuales',  to: 'admin_pages#reportes_bimensuales'
  get '/admin/reportes_finales',      to: 'admin_pages#reportes_finales'

  match '/admin/reportes_mensuales/:id/cambiar_estado/:estado_id',  to: 'monthly_reports#cambiar_estado', as: :cambiar_estado_reporte, via: :put
  match '/admin/reportes_bimensuales/:id/cambiar_estado/:estado_id',  to: 'bi_monthly_reports#cambiar_estado', as: :cambiar_estado_reporte_bim, via: :put
  match '/admin/reportes_finales/:id/cambiar_estado/:estado_id',  to: 'final_reports#cambiar_estado', as: :cambiar_estado_reporte_fin, via: :put
  get '/Convocatoria', to: 'admin_pages#update_convocatoria'
  scope "/admin" do
    resources :institucions
    resources :plantels
    resources :final_reports, except: [:create, :new, :index] do
      get 'print', to: "final_reports#print", on: :member
    end
    resources :inscripcions,        path: "inscripciones" do
      match 'update_observaciones',   to: 'inscripcions#update_observaciones', via: :put
      match 'update_status/:status',  to: 'inscripcions#update_status', as: 'update_status'
      get   'generar_nuevo_ncontrol', to: 'inscripcions#generar_nuevo_ncontrol', as: 'generar_ncontrol'
      get   'calcular_horas_servicio', to: 'inscripcions#calcular_horas_servicio', as: 'calcular_horas_servicio'
      get   'reportes_mensuales',     to: 'inscripcions#reportes_mensuales', on: :member
      get   'reportes_bimensuales',     to: 'inscripcions#reportes_bimensuales', on: :member
    end
    resources :articulos, path: 'Articulo_91' do
      match 'Actualizar/:status',     to: 'articulos#update_stat', as: :update_stat
      match 'update_observaciones',   to: 'articulos#update_observaciones', via: :put
    end
  end

  root to: 'public_pages#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/prestador.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: prestadors
#
#  id                 :integer          not null, primary key
#  nombre             :string(255)      not null
#  apaterno           :string(255)      not null
#  amaterno           :string(255)      not null
#  nacimiento         :date             not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  sexo               :string(255)
#  dCalle             :string(255)
#  dNumExt            :string(255)
#  dNumInt            :string(255)
#  dCP                :string(255)
#  dDelegacion        :string(255)
#  dColonia           :string(255)
#  telCasa            :string(255)
#  telCel             :string(255)
#  estudiante_uacm    :boolean          default(FALSE)
#  inscripcion_actual :integer
#  articulo_id        :integer
#

# -*- encoding : utf-8 -*-
class Prestador < ActiveRecord::Base
  attr_accessible :amaterno, :apaterno, :nacimiento, :nombre, :user_attributes,
  	:sexo, :dCalle, :dNumExt, :dNumInt, :dCP, :dDelegacion, :dColonia, :telCasa, :telCel,
  	:inscripcion_actual, :estudiante_uacm, :articulo_id
  	
  validates_presence_of :nombre, :amaterno, :apaterno, :nacimiento, :user,
  	:sexo, :dCalle, :dNumExt, :dCP, :dDelegacion, :dColonia
  
  # Relaciones
  has_one :user, dependent: :destroy
	accepts_nested_attributes_for :user

	has_many :inscripcions, dependent: :destroy

  has_one :articulo, dependent: :destroy

  
  def nombre_completo
    "#{self.nombre} #{self.apaterno} #{self.amaterno}"
  end

  def dnumero_completo
    numero = self.dNumExt
    numero += " | #{self.dNumInt}" if self.dNumInt
    numero
  end
end

app/controllers/prestadors_controller.rb
# -*- encoding : utf-8 -*-
class PrestadorsController < ApplicationController
	before_filter :require_login, except: [:create, :new]
	
	layout 'admin'

	def search
		authorize! :read, Prestador
		like = "LIKE"
		if ActiveRecord::Base.connection.adapter_name.downcase == "postgresql"
			like = "ILIKE"
		end
		query = "nombre #{like} ? OR apaterno LIKE ? OR amaterno LIKE ?"
		nombre = "%#{params[:nombre]}%"
		@prestadors = Prestador.page(params[:page]).where(query, nombre, nombre, nombre)
		flash.now[:error] = "Búsqueda sin resultados" unless @prestadors
		render :index
	end

	def index
		authorize! :read, Prestador
		@prestadors = Prestador.paginate(page: params[:page])
		flash.now[:error] = "Búsqueda sin resultados" unless @prestadors
	end

	def new
		@prestador = Prestador.new
		@prestador.build_user

		render layout: 'application'
	end

	def create
		@prestador = Prestador.new(params[:prestador])
		if @prestador.save
			flash[:success] = "Bienvenido a SiRASS!"
			auto_login(@prestador.user)
			redirect_back_or_to @prestador.user.user_page
		else
			flash.now[:error] = "Ha ocurrido un error registrando al prestador"
			render 'new', layout: 'application'
		end
	end

	def edit
		@prestador = Prestador.find_by_id(params[:id])
		if @prestador
			# Permitir que el usuario actualice su misma información
			if current_user == @prestador.user
				render layout: 'prestador'
			else
				# El usuario actual intenta actualizar la información de otro usuario
				# que no es él. Checar permisos
				authorize! :update, Prestador
			end
		else
			no_encontrado
		end
	end

	def update
		@prestador = Prestador.find(params[:id])
		# Si el password está en blanco quiere decir que no se desea actualizar
		check_password_update(params, :prestador)
		
		# Actualización de datos
		if @prestador.update_attributes(params[:prestador])
			flash[:success] = "Datos actualizados correctamente"
			redirect_to current_user.user_page
		else
			flash.now[:error] = "Ocurrió un error actualizando tus datos"
			render 'edit', layout: layoutForUser()
		end
	end

	def show
		@prestador = Prestador.find_by_id(params[:id])
		if @prestador
			@inscripcion = Inscripcion.find(@prestador.inscripcion_actual) if @prestador.inscripcion_actual
			@articulo = Articulo.find(@prestador.articulo_id) if @prestador.articulo_id
			# Autorizar acceso
			if current_user.prestador != @prestador
				authorize! :read, Prestador, message: 'No tienes permisos suficientes para ver esta página'
			else
				render layout: 'prestador'
			end			
		else
			no_encontrado
		end
	end

	def destroy
		Prestador.find(params[:id]).destroy
		flash[:success] = "Prestador borrado correctamente"
		redirect_to current_user.user_page
	end

	private
		def no_encontrado(msg = nil, page = nil)
			msg ||= "Prestador no encontrado"
			flash[:error] = msg
			page ||= current_user.user_page
			redirect_to page
		end

		def layoutForUser
			if current_user.prestador
				"prestador"
			elsif current_user.admin
				"admin"
			elsif current_user.institucion_user
				"institucion"
			else
				"application"
			end
		end
end

app/helpers/prestadors_helper.rb
# -*- encoding : utf-8 -*-
module PrestadorsHelper
	def current_status
		
	end
end

app/views/prestadors/_admin_btn.html.erb
<% size ||= 'large' %>
<div class="btn-group btn-block">
	<a href="#" class="btn <%= size %> btn-primary btn-block dropdown-toggle" data-toggle="dropdown">
		Administrar
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu pull-right">
		<li>
			<%= link_to edit_prestador_path(obj) do %>
			<i class="icon-pencil"></i>
			Editar
			<% end %>
		</li>
		<li>
			<%= link_to prestador_path(obj), method: :delete, confirm: 'Estás seguro?' do %>
			<i class="icon-trash"></i>
			Borrar
			<% end %>
		</li>
	</ul>
</div>

app/views/prestadors/_fields.html.erb
<div class="row">
	<div class="span6">
		<!-- Datos personales
		============================== -->
		<legend>Datos personales</legend>
		<%= f.input :nombre, placeholder: 'Juan Carlos' %>
		<%= f.input :apaterno, placeholder: 'Rodríguez' %>
		<%= f.input :amaterno, label: 'Apellido Materno', placeholder: 'Perea' %>
		<%= f.input :nacimiento, label: 'Fecha de nacimiento', as: :string,
			input_html: { 'data-behaviour' => 'datepicker', class: 'input-small', value: f.object.nacimiento } %>
		<%= f.input :sexo, collection: [:Masculino, :Femenino], as: :radio_buttons, item_wrapper_class: 'inline' %>
		<%= f.input :estudiante_uacm, as: :radio_buttons, item_wrapper_class: 'inline' %>
	</div> <!-- fin datos personales -->
	<div class="span6">
		<!-- Domicilio
		============================== -->
		<legend>Domicilio</legend>
		<%= f.input :dCalle, label: 'Calle', placeholder: 'Av. De las Culturas' %>
		<%= f.input :dNumExt, label: 'Número exterior/interior' do %>
			<%= f.input_field :dNumExt, placeholder: 'Exterior', class: "input-mini" %>
			<%= f.input_field :dNumInt, placeholder: 'Interior', class: "input-mini" %>
		<% end %>
		<%= f.input :dCP, label: 'Código postal', placeholder: '#####', input_html: {class: 'input-mini'} %>
		<%= f.input :dDelegacion, label: 'Delegación/Municipio', placeholder: 'Azcapotzalco' %>
		<%= f.input :dColonia, label: 'Colonia', placeholder: 'Clavería' %>
		<%= f.input :telCasa, label: 'Teléfono', placeholder: '12345678' %>
		<%= f.input :telCel, label: 'Celular', placeholder: '5512345678' %>
	</div> <!-- fin domicilio -->
</div> <!-- fin row -->

app/views/prestadors/_table.html.erb
<% if prestadors.any? %>
	<%= will_paginate %>
		<table class="table table-striped table-bordered table-hover" id="lista-prestadores">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Usuario</th>
					<th>Inscripción</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				<% prestadors.each do |prestador| %>
					<tr>
						<td>
							<%= link_to "#{prestador.nombre} #{prestador.apaterno} #{prestador.amaterno}", prestador %>
						</td>
						<td>
							<%= prestador.user.username %>
						</td>
						<td>
							<% if prestador.inscripcion_actual %>
								<%= link_to prestador.inscripcion_actual, inscripcion_path(prestador.inscripcion_actual), class: 'btn btn-block btn-warning' %>
							<% else %>
								<i class="icon-remove"></i>
							<% end %>
						</td>
						<td>
							<%= render 'admin_btn', obj: prestador, size: 'btn-mini' %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<%= will_paginate %>
<% else %>
<h1>No se encontraron prestadores</h1>
<% end %>

app/views/prestadors/edit.html.erb
<% provide(:title, 'Editar información de prestador') %>
<% provide(:sidebar_active, :editar) %>
<h1>Editar información</h1>
<%= render 'shared/error_messages', object: @prestador %>

<%= simple_form_for @prestador, html: { class: 'form-horizontal' },
	defaults: { input_html: { class: 'input-block-level' } } do |f| %>
	<!-- prestador fields -->
	<%= render 'prestadors/fields', f: f %>
	<div class="row form-vertical">
		<div class="span6">
			<!-- user fields -->
			<legend>Datos de usuario</legend>
			<%= f.simple_fields_for :user do |builder| %>
				<%= render 'users/fields', f: builder %>
			<% end %>
		</div>
	</div>
	<div class="form-actions">
		<%= button_tag "Actualizar", type: "submit", class: "btn btn-success btn-large" %>
	</div>
<% end %>

app/views/prestadors/index.html.erb
<% provide(:title, 'Lista de Prestadores') %>
<% provide(:sidebar_active, :prestadores) %>
<h1>Lista de Prestadores</h1>
<% if @prestadors.any? %>
	<%= will_paginate %>
		<table class="table table-striped table-bordered table-hover" id="lista-prestadores">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Usuario</th>
					<th>Inscripción</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				<% @prestadors.each do |prestador| %>
					<tr>
						<td>
							<%= link_to "#{prestador.nombre} #{prestador.apaterno} #{prestador.amaterno}", prestador %>
						</td>
						<td>
							<%= prestador.user.username %>
						</td>
						<td>
							<% if prestador.inscripcion_actual %>
								<%= link_to prestador.inscripcion_actual, inscripcion_path(prestador.inscripcion_actual), class: 'btn btn-block btn-warning' %>
							<% else %>
								<% if prestador.articulo_id %>
									<%= link_to prestador.articulo_id, articulos_path(prestador.articulo_id), class: 'btn btn-block btn-warning' %>
								<% else %>
									<i class="icon-remove"></i>
								<% end %>
							<% end %>
						</td>
						<td>
							<%= render 'admin_btn', obj: prestador, size: 'btn-mini' %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<%= will_paginate %>
<% else %>
<h1>No se encontraron prestadores</h1>
<% end %>

app/views/prestadors/new.html.erb
<% provide(:title, 'Registro de prestador') %>
<h1>Registro de prestador</h1>
<%= render 'shared/error_messages', object: @prestador %>

<%= simple_form_for @prestador, html: { class: 'form-horizontal' },
	defaults: { input_html: { class: 'input-block-level' } } do |f| %>
	<!-- prestador fields -->
	<%= render 'prestadors/fields', f: f %>
	<div class="row form-vertical">
		<div class="span6">
			<!-- user fields -->
			<legend>Datos de usuario</legend>
			<%= f.simple_fields_for :user do |builder| %>
				<%= render 'users/fields', f: builder %>
			<% end %>

		</div>
	</div>
	<div class="form-actions">
		<%= button_tag "Registrarse", type: "submit", class: "btn btn-success btn-large" %>
		<%= button_tag "Limpiar campos", type: "reset", class: "btn btn-large" %>
	</div>
<% end %>

app/views/prestadors/show.html.erb
<h1>Información del prestador</h1>
<div class="row well-show">
	<div class="span4">
		<p>
			<strong>Usuario:</strong> <%= @prestador.user.username %>
		</p>
		<p>
			<strong>Email:</strong> <%= @prestador.user.email %>
		</p>
		<p>
			<strong>Nombre:</strong> <%= "#{@prestador.nombre} #{@prestador.apaterno} #{@prestador.amaterno}" %>
		</p>
		<p>
			<strong>Edad:</strong> <%= distance_of_time_in_words_to_now(@prestador.nacimiento) %>
		</p>
		<p>
			<strong>Sexo:</strong> <%= @prestador.sexo %>
		</p>

	</div>
	<% if can? :manage, @prestador %>
		<div class="span2 pull-right">
			<%= render 'admin_btn', obj: @prestador, size: 'btn-large' %>
		</div>
	<% end %>
</div>

<h2>Domicilio</h2>
<div class="row well-show">
	<div class="span4">
		<p>
			<strong>Calle:</strong> <%= @prestador.dCalle %>
		</p>
		<p class="clearfix">
			<strong>Número ext./int.:</strong> <%= @prestador.dNumExt %> <%= "| #{@prestador.dNumInt}" %>
		</p>
		<p>
			<strong>Código postal:</strong> <%= @prestador.dCP %>
		</p>
	</div>
	<div class="span4">
		<p>
			<strong>Delegación:</strong> <%= @prestador.dDelegacion %>
		</p>
		<p>
			<strong>Colonia:</strong> <%= @prestador.dColonia %>
		</p>
		<p>
			<strong>Teléfono:</strong> <%= @prestador.telCasa %>
		</p>
		<p>
			<strong>Celular:</strong> <%= @prestador.telCel %>
		</p>
	</div>
</div>

<% if @inscripcion %>
	<h2>Inscripción</h2>
	<p>
		Este usuario tiene una solicitud de inscripcion al programa:
		<blockquote>
			<%= @inscripcion.cprograma.nombre %>
		</blockquote>
		<strong>Estado:</strong> <span class="label <%= label_color_for_inscripcion(@inscripcion) %>"><%= @inscripcion.estado_inscripcion.descripcion %></span>
	</p>
	<% if can? :manage, Inscripcion %>
		<p>
			<%= link_to inscripcion_path(@prestador.inscripcion_actual), class: 'btn btn-warning' do %>
				<i class="icon-info-sign"></i>
				Ver detalles
			<% end %>
		</p>
		<p>
			<%= render 'shared/back_button', link: prestadors_path %>
		</p>
	<% else %>
		<%= link_to mi_inscripcion_path, class: 'btn btn-warning' do %>
			<i class="icon-info-sign"></i>
			Ver detalles
		<% end %>
	<% end %>
<% else %>
<% if @articulo %>
	<h2>Inscripción</h2>
	<p>
		Este usuario tiene una solicitud de inscripción vía Artículo 91
		<strong>Estado:</strong> <span class="label <%= label_color_for_inscripcion(@articulo) %>"><%= @articulo.estado_inscripcion.descripcion %></span>
	</p>
	<% if can? :manage, Articulo %>
		<p>
			<%= link_to articulo_path(@prestador.articulo_id), class: 'btn btn-warning' do %>
				<i class="icon-info-sign"></i>
				Ver detalles
			<% end %>
		</p>
		<p>
			<%= render 'shared/back_button', link: prestadors_path %>
		</p>
	<% else %>
		<%= link_to mi_inscripcion_art_path, class: 'btn btn-warning' do %>
			<i class="icon-info-sign"></i>
			Ver detalles
		<% end %>
	<% end %>
<% else %>
<p class="lead">Este usuario aún no ha enviado ninguna solicitud de inscripción a un programa de servicio social.</p>
<% end %>
<% end %>